---
title: "Mental Health"
author: ""
date: "15/04/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      comment = "#",
                     # results = "hide",
                      message = F,
                      warning = F,
                      cache = F, 
                      eval = T)

```

```{r}
#install.packages("ggthemes")
#install.packages("reshape2")
#install.packages("RColorBrewer")
#install.packages("ggplot2")

library(ggplot2)
library(ggthemes)
library(tidyverse)
library(reshape2)
library(RColorBrewer)

mental.data <- read.csv('mental_health_tech.csv',fileEncoding = 'GBK')
dim(mental.data)

```


# 1. How different groups of people(by age, sex) perform differently in mental health condition.
```{r}
## data preprocessing
# gender info
temp <- mental.data[, grep('gender', colnames(mental.data))]
temp[! toupper(str_sub(temp, 1,1)) %in% c('F', 'M','W') ] <- 'Others'
temp[ toupper(str_sub(temp, 1,1)) %in% c('F', 'W') ] <- 'Female'
temp[ toupper(str_sub(temp, 1,1)) %in% c('M') ] <- 'Male'
gender <- temp
# age
age <- mental.data[, grep('What.is.your.age.', colnames(mental.data))]
breaks <- c(10*c(1:7))
age_category <-  cut(as.numeric(age), breaks,include.lowest = TRUE, right = FALSE, dig.lab=10)
# condition
condition <- mental.data[grep('condition', colnames(mental.data))]
colnames(condition)
condition.diagnosed <- condition$Have.you.been.diagnosed.with.a.mental.health.condition.by.a.medical.professional.
condition.type <- condition$If.so..what.condition.s..were.you.diagnosed.with.
temp <-  str_split(condition.type, '[|]', simplify = T)

# data for plot
plotdata <- data.frame(cbind(gender = gender, age = age, age_category = as.character(age_category),
                  condition.diagnosed = condition.diagnosed,temp))
plotdata_long <- melt(plotdata, id.vars = c('gender', 'age','age_category', 'condition.diagnosed'))
colnames(plotdata_long)

## age distribution
plotdata=plotdata[-which(plotdata$age=="323"),]
ggplot(plotdata) +
    geom_boxplot(aes(x = gender,y =age,  fill = gender, group = gender,)) +
    scale_fill_brewer(palette =  'Accent') +
    theme_bw()+ggtitle("Age Distribution by Sex")+xlab("Gender")+ylab("Age")+theme(plot.title = element_text(hjust = 0.5))


## condition.diagnosed
library(ggpubr)
figure=ggpubr::ggarrange(
  ggplot(plotdata) +
    geom_bar(aes(x = gender, fill = condition.diagnosed), position = 'dodge') +
    scale_fill_brewer() +
    theme_bw()+ylab("Number of People")+xlab("Gender")  ,
  
  ggplot(plotdata) +
    geom_bar(aes(x = age_category,  fill = condition.diagnosed), position = 'dodge') +
    scale_fill_brewer() +
    theme_bw()+ylab("Number of People")+
    theme(axis.text.x = element_text(angle = 90)), common.legend = T
)
annotate_figure(figure,
               top = text_grob("Condition Diagnosed by Sex and Age",face="bold"))

## condition plot
col <- colorRampPalette(brewer.pal(9, 'Set1'))(6)
plotdata_long <- plotdata_long %>%
  filter(! value == '')

a=unique(plotdata_long$value);a
for(i in 1:length(a)){
  if (i != 1 & i !=2 & i!=4 & i!=8  & i!=9) {
  plotdata_long[which(plotdata_long$value==a[i]),"value"]<-"others"
    }
}

ggplot(plotdata_long) +
  geom_bar(aes(x = age_category, fill = value),position = 'stack') +
  facet_wrap(~gender) +
  scale_fill_manual(values=col) +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        legend.text = element_text(size = 9),
        axis.text.x = element_text(angle = 90))+
  guides(fill = guide_legend(ncol = 2,
                             keywidth = unit(4,'mm'),
                             keyheight = unit(4,'mm')))+ylab("Number of People")+ggtitle("Specific Mental Health Disorders by Sex and Age")+theme(plot.title = element_text(hjust = 0.5))


```


